# Auto-generated Packer template for demo-linux
# Generated by v2-ami-automation
# Generated at: 2025-11-21T18:12:43Z
#
# Lab: demo-linux
# OS: ubuntu-24
# Git Hash: c1d88a3

packer {
  required_version = ">= 1.8.0"

  required_plugins {
    amazon = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/amazon"
    }
  }
}

# Local variables for naming and tagging
locals {
  timestamp = regex_replace(timestamp(), "[- TZ:]", "")
  ami_name  = "lab-demo-linux-${local.timestamp}"

  common_tags = {
    Name             = "lab-demo-linux-${local.timestamp}"
    Lab              = "lab-demo-linux-c1d88a3"
    OS               = var.os_type
    CreatedAt        = timestamp()
    CreatedBy        = "packer"
    Environment      = "laboratory"
    ManagedBy        = "v2-ami-automation"
    SourceAmiId      = var.source_ami
    SourceAmiName    = var.source_ami_name
  }
}

# Source configuration for Amazon EBS
source "amazon-ebs" "demo-linux" {
  ami_name      = local.ami_name
  instance_type = var.instance_type
  region        = var.region
  source_ami    = var.source_ami

    ssh_username = "ubuntu"

  # EBS volume configuration
  launch_block_device_mappings {
    device_name           = "/dev/sda1"
    volume_size           = var.volume_size
    volume_type           = var.volume_type
    delete_on_termination = true
    encrypted             = var.encrypt_boot
  }

  # AMI configuration
  ami_description = "Laboratory AMI for demo-linux - Built with Packer"

  # Tags applied to the AMI
  tags = local.common_tags

  # Tags applied to the temporary instance during build
  run_tags = merge(
    local.common_tags,
    {
      Name = "packer-builder-demo-linux"
      Type = "temporary"
    }
  )

  # Tags applied to volumes
  snapshot_tags = local.common_tags

  # Build configuration
  ssh_timeout = "10m"

  # Security - use temporary security group
  temporary_security_group_source_public_ip = true
}

# Build configuration
build {
  name    = "demo-linux-build"
  sources = ["source.amazon-ebs.demo-linux"]


  # Copy build files to the instance
  provisioner "shell" {
      inline = [
        "mkdir -p /tmp/build-files",
        #"chmod 777 /tmp/build-files"
      ]
  }
  provisioner "file" {
    source      = "${path.root}/build-files/"
    destination = "/tmp/build-files/"
  }

  # Execute the main setup script
  provisioner "shell" {
    script = "${path.root}/userdata.sh"
    environment_vars = [
      "LAB_NAME=demo-linux",
      "OS_TYPE=ubuntu-24",
      "BUILD_FILES=/tmp/build-files"
    ]
  }

  # Clean up sensitive data and prepare for AMI
  provisioner "shell" {
    inline = [
      "echo 'Cleaning up for AMI creation...'",
      "sudo rm -rf /tmp/*",
      "sudo rm -rf /var/tmp/*",
      "sudo rm -f /root/.bash_history",
      "sudo rm -f /home/*/.bash_history",
      "sudo find /var/log -type f -exec truncate -s 0 {} \\;",
      "echo 'Cleanup completed'"
    ]
  }

  # Post-processor to manifest AMI details
  post-processor "manifest" {
    output     = "${path.root}/packer-manifest.json"
    strip_path = true
    custom_data = {
      lab_name    = "demo-linux"
      os_type     = "ubuntu-24"
      git_hash    = "c1d88a3"
      build_time  = timestamp()
      ami_name    = local.ami_name
    }
  }
}
