# Auto-generated Packer template for {{LAB_NAME}} (Windows)
# Generated by AMI_AUTOMATOR
# Generated at: {{TIMESTAMP_ISO}}
#
# Lab: {{LAB_NAME}}
# OS: {{OS_TYPE}}
# Git Hash: {{GIT_HASH}}

packer {
  required_version = ">= 1.8.0"

  required_plugins {
    amazon = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/amazon"
    }
  }
}

# Local variables for naming and tagging
locals {
  timestamp = regex_replace(timestamp(), "[- TZ:]", "")
  ami_name  = "lab-{{LAB_NAME}}-${local.timestamp}"

  common_tags = {
    Name             = "lab-{{LAB_NAME}}-${local.timestamp}"
    Lab              = "lab-{{LAB_NAME}}-{{GIT_HASH}}"
    OS               = var.os_type
    CreatedAt        = timestamp()
    CreatedBy        = "packer"
    Environment      = "laboratory"
    ManagedBy        = "v2-ami-automation"
    SourceAmiId      = var.source_ami
    SourceAmiName    = var.source_ami_name
  }
}

# Source configuration for Amazon EBS (Windows)
source "amazon-ebs" "{{LAB_NAME}}" {
  ami_name      = local.ami_name
  instance_type = var.instance_type
  region        = var.region
  source_ami    = var.source_ami

  {{COMMUNICATOR_CONFIG}}

  # Windows requires more time for WinRM to be ready
  user_data_file = ""

  # EBS volume configuration
  launch_block_device_mappings {
    device_name           = "/dev/sda1"
    volume_size           = var.volume_size
    volume_type           = var.volume_type
    delete_on_termination = true
    encrypted             = var.encrypt_boot
  }

  # AMI configuration
  ami_description = "Laboratory AMI for {{LAB_NAME}} - Built with Packer"

  # Tags applied to the AMI
  tags = local.common_tags

  # Tags applied to the temporary instance during build
  run_tags = merge(
    local.common_tags,
    {
      Name = "packer-builder-{{LAB_NAME}}"
      Type = "temporary"
    }
  )

  # Tags applied to volumes
  snapshot_tags = local.common_tags

  # Build configuration for Windows
  # WinRM timeout is configured via winrm_timeout in communicator config
}


# Build configuration
build {
  name    = "{{LAB_NAME}}-build"
  sources = ["source.amazon-ebs.{{LAB_NAME}}"]

  # Create build files directory
  provisioner "powershell" {
    inline = [
      "New-Item -ItemType Directory -Force -Path C:\\temp\\build-files | Out-Null",
      "Write-Host 'Build files directory created'"
    ]
  }

  # Copy build files to the instance
  provisioner "file" {
    source      = "${path.root}/build-files/"
    destination = "C:/temp/build-files/"
  }

  # Execute the main setup script
  provisioner "powershell" {
    script = "${path.root}/{{USERDATA_SCRIPT}}"
    environment_vars = [
      "LAB_NAME={{LAB_NAME}}",
      "OS_TYPE={{OS_TYPE}}",
      "BUILD_FILES=C:\\temp\\build-files"
    ]
  }

  # Clean up sensitive data and prepare for AMI
  provisioner "powershell" {
    inline = [
      "Write-Host 'Cleaning up for AMI creation...'",
      "Remove-Item -Path C:\\temp\\* -Recurse -Force -ErrorAction SilentlyContinue",
      "Remove-Item -Path C:\\Windows\\Temp\\* -Recurse -Force -ErrorAction SilentlyContinue",
      "Clear-History",
      "Remove-Item -Path $env:USERPROFILE\\AppData\\Roaming\\Microsoft\\Windows\\PowerShell\\PSReadLine\\* -Force -ErrorAction SilentlyContinue",
      "Get-EventLog -LogName * | ForEach-Object { Clear-EventLog $_.Log } -ErrorAction SilentlyContinue",
      "Write-Host 'Cleanup completed'"
    ]
  }

  # Sysprep for Windows (optional - uncomment if needed)
  # provisioner "powershell" {
  #   inline = [
  #     "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Scripts\\InitializeInstance.ps1 -Schedule",
  #     "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Scripts\\SysprepInstance.ps1 -NoShutdown"
  #   ]
  # }

  # Post-processor to manifest AMI details
  post-processor "manifest" {
    output     = "${path.root}/packer-manifest.json"
    strip_path = true
    custom_data = {
      lab_name    = "{{LAB_NAME}}"
      os_type     = "{{OS_TYPE}}"
      git_hash    = "{{GIT_HASH}}"
      build_time  = timestamp()
    }
  }
}
