# Auto-generated Packer template for {{LAB_NAME}}
# Generated by AMI_AUTOMATOR
# Generated at: {{TIMESTAMP_ISO}}
#
# Lab: {{LAB_NAME}}
# OS: {{OS_TYPE}}
# Git Hash: {{GIT_HASH}}

packer {
  required_version = ">= 1.8.0"

  required_plugins {
    amazon = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/amazon"
    }
  }
}

# Local variables for naming and tagging
locals {
  timestamp = regex_replace(timestamp(), "[- TZ:]", "")
  ami_name  = "lab-{{LAB_NAME}}-${local.timestamp}"

  common_tags = {
    Name             = "{{LAB_NAME}}-${local.timestamp}"
    Laboratory       = "{{LAB_NAME}}"
    OS               = var.os_type
    CreatedAt        = timestamp()
    CreatedBy        = "packer"
    ManagedBy        = "ami-automation"
    SourceAmiId      = var.source_ami
    SourceAmiName    = var.source_ami_name
    CommitHash       = "{{GIT_HASH}}"
    BuildPackerMachine = "false"
  }
}

# Source configuration for Amazon EBS
source "amazon-ebs" "{{LAB_NAME}}" {
  ami_name      = local.ami_name
  instance_type = var.instance_type
  region        = var.region
  source_ami    = var.source_ami

  {{COMMUNICATOR_CONFIG}}

  # EBS volume configuration
  launch_block_device_mappings {
    device_name           = "/dev/sda1"
    volume_size           = var.volume_size
    volume_type           = var.volume_type
    delete_on_termination = true
    encrypted             = var.encrypt_boot
  }

  # AMI configuration
  ami_description = "Laboratory AMI for {{LAB_NAME}} - Built with Packer"

  # Tags applied to the AMI
  tags = local.common_tags

  # Tags applied to the temporary instance during build
  run_tags = merge(
    local.common_tags,
    {
      Name = "packer-builder-{{LAB_NAME}}"
      BuildPackerMachine = "true"
      Laboratory         = "{{LAB_NAME}}"
      CommitHash       = "{{GIT_HASH}}"
    }
  )

  # Tags applied to volumes
  snapshot_tags = local.common_tags

  # Build configuration
  ssh_timeout = "10m"

  # Security - use temporary security group
  temporary_security_group_source_public_ip = true
}

# Build configuration
build {
  name    = "{{LAB_NAME}}-build"
  sources = ["source.amazon-ebs.{{LAB_NAME}}"]


  # Copy build files to the instance
  provisioner "shell" {
      inline = [
        "mkdir -p /tmp/build-files",
      ]
  }
  provisioner "file" {
    source      = "${path.root}/build-files/"
    destination = "/tmp/build-files/"
  }

  # Move files to /root with sudo
  provisioner "shell" {
    inline = [
      "sudo mkdir -p /root/build-files",
      "sudo mv /tmp/build-files/* /root/build-files/",
      "sudo chown -R root:root /root/build-files"
    ]
  }

  # Execute the main setup script
  provisioner "shell" {
    script = "${path.root}/{{USERDATA_SCRIPT}}"
    environment_vars = [
      "LAB_NAME={{LAB_NAME}}",
      "OS_TYPE={{OS_TYPE}}",
      "BUILD_FILES=/tmp/build-files"
    ]
    execute_command = "sudo {{ .Vars }} sh -c '{{ .Path }}'"
  }

  # Clean up sensitive data and prepare for AMI
  provisioner "shell" {
    inline = [
      "echo 'Cleaning up for AMI creation...'",
      "sudo rm -rf /tmp/*",
      "sudo rm -rf /var/tmp/*",
      "sudo rm -f /root/.bash_history",
      "sudo rm -f /home/*/.bash_history",
      "sudo find /var/log -type f -exec truncate -s 0 {} \\;",
      "echo 'Cleanup completed'"
    ]
  }

  # Post-processor to manifest AMI details
  post-processor "manifest" {
    output     = "${path.root}/packer-manifest.json"
    strip_path = true
    custom_data = {
      lab_name    = "{{LAB_NAME}}"
      os_type     = "{{OS_TYPE}}"
      git_hash    = "{{GIT_HASH}}"
      build_time  = timestamp()
      ami_name    = local.ami_name
    }
  }
}
