# Auto-generated variables file for {{LAB_NAME}}
# Generated by v2-ami-automation
#
# This file defines all variables used in the Packer template.
# Modify these values to customize your AMI build.

variable "lab_name" {
  type        = string
  description = "Name of the laboratory"
  default     = "{{LAB_NAME}}"
}

variable "os_type" {
  type        = string
  description = "Operating system type"
  default     = "{{OS_TYPE}}"
}

variable "source_ami" {
  type        = string
  description = "Source AMI ID to build from"
  default     = "{{SOURCE_AMI}}"
}

variable "source_ami_name" {
  type        = string
  description = "Source AMI name for tagging"
  default     = "{{SOURCE_AMI_NAME}}"
}

variable "instance_type" {
  type        = string
  description = "EC2 instance type for building the AMI"
  default     = "t3.medium"
}

variable "region" {
  type        = string
  description = "AWS region for building the AMI"
  default     = "us-east-1"
}

variable "volume_size" {
  type        = number
  description = "Root volume size in GB"
  default     = 30
}

variable "volume_type" {
  type        = string
  description = "Root volume type"
  default     = "gp3"
}

variable "encrypt_boot" {
  type        = bool
  description = "Encrypt the root volume"
  default     = true
}
