# Auto-generated Packer template for jekroast (Windows)
# Generated by AMI_AUTOMATOR
# Generated at: 2025-12-15T15:44:33Z
#
# Lab: jekroast
# OS: windows-server-2022
# Git Hash: 3ce770d

packer {
  required_version = ">= 1.8.0"

  required_plugins {
    amazon = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/amazon"
    }
  }
}

# Local variables for naming and tagging
locals {
  timestamp = regex_replace(timestamp(), "[- TZ:]", "")
  ami_name  = "jekroast-${local.timestamp}"

  common_tags = {
    Name             = "jekroast-${local.timestamp}"
    Laboratory       = "jekroast"
    OS               = var.os_type
    CreatedAt        = timestamp()
    CreatedBy        = "packer"
    ManagedBy        = "ami-automation"
    SourceAmiId      = var.source_ami
    SourceAmiName    = var.source_ami_name
    CommitHash       = "3ce770d"
    BuildPackerMachine = "false"
  }
}

# Source configuration for Amazon EBS (Windows)
source "amazon-ebs" "jekroast" {
  ami_name      = local.ami_name
  instance_type = var.instance_type
  region        = var.region
  source_ami    = var.source_ami

    communicator = "winrm"
  winrm_username = "Administrator"
  winrm_port = 5986
  winrm_insecure = true
  winrm_use_ssl = true
  winrm_timeout = "10m"

  # Additional WinRM settings for better reliability
  winrm_use_ntlm = true

  # Windows WinRM configuration via user_data
  # This script configures WinRM for Packer to connect
  user_data = <<EOF
<powershell>
# Function to enable and configure WinRM
function Enable-WinRMConfiguration {
    [CmdletBinding()]
    param (
        [Parameter()]
        [switch]$EnableHTTPS,

        [Parameter()]
        [switch]$AllowAllHosts,

        [Parameter()]
        [switch]$SkipNetworkCheck
    )

    try {

        $params = @{
            Force = $true
            SkipNetworkProfileCheck = $SkipNetworkCheck
        }

        Enable-PSRemoting @params

        Set-Service -Name winrm -StartupType Automatic

        Set-Item -Path WSMan:\localhost\Client\TrustedHosts -Value * -Force

        if ($AllowAllHosts) {
            winrm set winrm/config/client '@{TrustedHosts="*"}'
        }

        winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="1024"}'

        if ($EnableHTTPS) {
            Write-Host "Configuring HTTPS listener for WinRM..." -ForegroundColor Yellow

            $certificateName = $env:COMPUTERNAME
            $certificate = New-SelfSignedCertificate -DnsName $certificateName -CertStoreLocation Cert:\LocalMachine\My

            $thumbprint = $certificate.Thumbprint
            $command = "winrm create winrm/config/Listener?Address=*+Transport=HTTPS '@{Hostname=`"$certificateName`";CertificateThumbprint=`"$thumbprint`"}'"
            Invoke-Expression $command

            Write-Host "Creating firewall rule for WinRM over HTTPS..." -ForegroundColor Yellow
            New-NetFirewallRule -DisplayName "Windows Remote Management (HTTPS-In)" -Name "Windows Remote Management (HTTPS-In)" -Profile Any -LocalPort 5986 -Protocol TCP -Direction Inbound
        }

        $service = Get-Service -Name WinRM
        if ($service.Status -ne 'Running') {
            Write-Host "Starting WinRM service..." -ForegroundColor Yellow
            Start-Service -Name WinRM
        }

        Write-Host "`nVerifying WinRM configuration:" -ForegroundColor Cyan
        winrm enumerate winrm/config/listener

        Write-Host "`nWinRM service status:" -ForegroundColor Cyan
        Get-Service -Name WinRM | Format-Table -Property Name, Status, StartType

        Write-Host "`nWinRM firewall rules:" -ForegroundColor Cyan
        Get-NetFirewallRule -DisplayName "Windows Remote Management*" | Format-Table -Property DisplayName, Enabled, Direction, Action

        Write-Host "`nWinRM has been successfully configured!" -ForegroundColor Green
        Write-Host "You can now connect to this machine using: Enter-PSSession -ComputerName $env:COMPUTERNAME" -ForegroundColor Green
        if ($EnableHTTPS) {
            Write-Host "For HTTPS connection use: Enter-PSSession -ComputerName $env:COMPUTERNAME -UseSSL" -ForegroundColor Green
        }
    }
    catch {
        Write-Error "An error occurred while configuring WinRM: $_"
    }
}

# Set execution policy and run the configuration
Set-ExecutionPolicy Unrestricted -Scope LocalMachine -Force -ErrorAction Ignore
Write-Host "Setting up WinRM for Packer..."

# Execute the function with parameters
Enable-WinRMConfiguration -EnableHTTPS -AllowAllHosts -SkipNetworkCheck

Write-Host "WinRM setup completed!"
</powershell>
EOF

  # EBS volume configuration
  launch_block_device_mappings {
    device_name           = "/dev/sda1"
    volume_size           = var.volume_size
    volume_type           = var.volume_type
    delete_on_termination = true
    encrypted             = var.encrypt_boot
  }

  # AMI configuration
  ami_description = "Laboratory AMI for jekroast - Built with Packer"

  # Tags applied to the AMI
  tags = local.common_tags

  # Tags applied to the temporary instance during build
  run_tags = merge(
    local.common_tags,
    {
      Name = "packer-builder-jekroast"
      BuildPackerMachine = "true"
      Laboratory         = "jekroast"
      CommitHash       = "3ce770d"
    }
  )

  # Tags applied to volumes
  snapshot_tags = local.common_tags

  # Build configuration for Windows
  # WinRM timeout is configured via winrm_timeout in communicator config
}


# Build configuration
build {
  name    = "jekroast-build"
  sources = ["source.amazon-ebs.jekroast"]

  # Create build files directory
  provisioner "powershell" {
    inline = [
      "New-Item -ItemType Directory -Force -Path C:\\temp\\build-files | Out-Null",
      "Write-Host 'Build files directory created'"
    ]
  }

  # Copy build files to the instance
  provisioner "file" {
    source      = "${path.root}/build-files/"
    destination = "C:/temp/build-files/"
  }

  provisioner "powershell" {
    inline = [
      # Desativa a proteção em tempo real antes de rodar o script
      "Set-MpPreference -DisableRealtimeMonitoring $true",
    ]
  }

  # Execute part 1 of setup script
  provisioner "powershell" {
    script = "${path.root}/split-userdata-1.ps1"
    environment_vars = [
      "LAB_NAME=jekroast",
      "OS_TYPE=windows-server-2022",
      "BUILD_FILES=C:\\temp\\build-files"
    ]
  }

  # Restart Windows
  provisioner "windows-restart" {
    restart_timeout = "10m"
  }
  # Execute part 2 of setup script
  provisioner "powershell" {
    script = "${path.root}/split-userdata-2.ps1"
    environment_vars = [
      "LAB_NAME=jekroast",
      "OS_TYPE=windows-server-2022",
      "BUILD_FILES=C:\\temp\\build-files"
    ]
  }

  # Restart Windows
  provisioner "windows-restart" {
    restart_timeout = "10m"
  }
  # Execute part 3 of setup script
  provisioner "powershell" {
    script = "${path.root}/split-userdata-3.ps1"
    environment_vars = [
      "LAB_NAME=jekroast",
      "OS_TYPE=windows-server-2022",
      "BUILD_FILES=C:\\temp\\build-files"
    ]
  }

  # Clean up sensitive data and prepare for AMI
  provisioner "powershell" {
    inline = [
      "Write-Host 'Cleaning up for AMI creation...'",
      "Remove-Item -Path C:\\temp\\* -Recurse -Force -ErrorAction SilentlyContinue",
      "Remove-Item -Path C:\\Windows\\Temp\\* -Recurse -Force -ErrorAction SilentlyContinue",
      "Clear-History",
      "Remove-Item -Path $env:USERPROFILE\\AppData\\Roaming\\Microsoft\\Windows\\PowerShell\\PSReadLine\\* -Force -ErrorAction SilentlyContinue",
      "Get-EventLog -LogName * | ForEach-Object { Clear-EventLog $_.Log } -ErrorAction SilentlyContinue",
      "Write-Host 'Cleanup completed'"
    ]
  }

  # Sysprep for Windows (optional - uncomment if needed)
  # provisioner "powershell" {
  #   inline = [
  #     "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Scripts\\InitializeInstance.ps1 -Schedule",
  #     "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Scripts\\SysprepInstance.ps1 -NoShutdown"
  #   ]
  # }

  # Post-processor to manifest AMI details
  post-processor "manifest" {
    output     = "${path.root}/packer-manifest.json"
    strip_path = true
    custom_data = {
      lab_name    = "jekroast"
      os_type     = "windows-server-2022"
      git_hash    = "3ce770d"
      build_time  = timestamp()
    }
  }
}
