# Auto-generated Packer template for test-windows (Windows)
# Generated by AMI_AUTOMATOR
# Generated at: 2025-12-01T18:20:53Z
#
# Lab: test-windows
# OS: windows-server-2022
# Git Hash: 9723951

packer {
  required_version = ">= 1.8.0"

  required_plugins {
    amazon = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/amazon"
    }
  }
}

# Local variables for naming and tagging
locals {
  timestamp = regex_replace(timestamp(), "[- TZ:]", "")
  ami_name  = "lab-test-windows-${local.timestamp}"

  common_tags = {
    Name             = "lab-test-windows-${local.timestamp}"
    Lab              = "lab-test-windows-9723951"
    OS               = var.os_type
    CreatedAt        = timestamp()
    CreatedBy        = "packer"
    Environment      = "laboratory"
    ManagedBy        = "v2-ami-automation"
    SourceAmiId      = var.source_ami
    SourceAmiName    = var.source_ami_name
  }
}

# Source configuration for Amazon EBS (Windows)
source "amazon-ebs" "test-windows" {
  ami_name      = local.ami_name
  instance_type = var.instance_type
  region        = var.region
  source_ami    = var.source_ami

    communicator = "winrm"
  winrm_username = "Administrator"
  winrm_insecure = true
  winrm_use_ssl = true
  winrm_timeout = "30m"

  # Additional WinRM settings for better reliability
  winrm_use_ntlm = true

  # Windows WinRM configuration via user_data
  # This script configures WinRM for Packer to connect
  user_data = <<EOF
<powershell>
# Configure WinRM for Packer
Write-Host "Setting up WinRM for Packer..."

# Set execution policy
Set-ExecutionPolicy Unrestricted -Scope LocalMachine -Force -ErrorAction Ignore

# Don't set network location to Public
# Skip the network location detection
New-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Network\NewNetworkWindowOff" -ErrorAction Ignore

# Remove HTTP listener
Remove-Item -Path WSMan:\Localhost\listener\listener* -Recurse -ErrorAction Ignore

# Create a self-signed certificate
$Cert = New-SelfSignedCertificate -CertstoreLocation Cert:\LocalMachine\My -DnsName "packer"
New-Item -Path WSMan:\LocalHost\Listener -Transport HTTPS -Address * -CertificateThumbPrint $Cert.Thumbprint -Force

# Configure WinRM
winrm quickconfig -q
winrm set "winrm/config" '@{MaxTimeoutms="1800000"}'
winrm set "winrm/config/winrs" '@{MaxMemoryPerShellMB="1024"}'
winrm set "winrm/config/service" '@{AllowUnencrypted="true"}'
winrm set "winrm/config/service/auth" '@{Basic="true"}'
winrm set "winrm/config/client" '@{AllowUnencrypted="true"}'
winrm set "winrm/config/client/auth" '@{Basic="true"}'
winrm set "winrm/config/listener?Address=*+Transport=HTTPS" "@{Port=`"5986`";Hostname=`"packer`";CertificateThumbprint=`"$($Cert.Thumbprint)`"}"

# Open Firewall
netsh advfirewall firewall add rule profile=any name="WinRM HTTPS" dir=in localport=5986 protocol=TCP action=allow

# Restart WinRM
net stop winrm
net start winrm

Write-Host "WinRM setup completed!"
</powershell>
EOF

  # EBS volume configuration
  launch_block_device_mappings {
    device_name           = "/dev/sda1"
    volume_size           = var.volume_size
    volume_type           = var.volume_type
    delete_on_termination = true
    encrypted             = var.encrypt_boot
  }

  # AMI configuration
  ami_description = "Laboratory AMI for test-windows - Built with Packer"

  # Tags applied to the AMI
  tags = local.common_tags

  # Tags applied to the temporary instance during build
  run_tags = merge(
    local.common_tags,
    {
      Name = "packer-builder-test-windows"
      Type = "temporary"
    }
  )

  # Tags applied to volumes
  snapshot_tags = local.common_tags

  # Build configuration for Windows
  # WinRM timeout is configured via winrm_timeout in communicator config
}


# Build configuration
build {
  name    = "test-windows-build"
  sources = ["source.amazon-ebs.test-windows"]

  # Create build files directory
  provisioner "powershell" {
    inline = [
      "New-Item -ItemType Directory -Force -Path C:\\temp\\build-files | Out-Null",
      "Write-Host 'Build files directory created'"
    ]
  }

  # Copy build files to the instance
  provisioner "file" {
    source      = "${path.root}/build-files/"
    destination = "C:/temp/build-files/"
  }

  # Execute the main setup script
  provisioner "powershell" {
    script = "${path.root}/userdata.ps1"
    environment_vars = [
      "LAB_NAME=test-windows",
      "OS_TYPE=windows-server-2022",
      "BUILD_FILES=C:\\temp\\build-files"
    ]
  }

  # Clean up sensitive data and prepare for AMI
  provisioner "powershell" {
    inline = [
      "Write-Host 'Cleaning up for AMI creation...'",
      "Remove-Item -Path C:\\temp\\* -Recurse -Force -ErrorAction SilentlyContinue",
      "Remove-Item -Path C:\\Windows\\Temp\\* -Recurse -Force -ErrorAction SilentlyContinue",
      "Clear-History",
      "Remove-Item -Path $env:USERPROFILE\\AppData\\Roaming\\Microsoft\\Windows\\PowerShell\\PSReadLine\\* -Force -ErrorAction SilentlyContinue",
      "Get-EventLog -LogName * | ForEach-Object { Clear-EventLog $_.Log } -ErrorAction SilentlyContinue",
      "Write-Host 'Cleanup completed'"
    ]
  }

  # Sysprep for Windows (optional - uncomment if needed)
  # provisioner "powershell" {
  #   inline = [
  #     "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Scripts\\InitializeInstance.ps1 -Schedule",
  #     "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Scripts\\SysprepInstance.ps1 -NoShutdown"
  #   ]
  # }

  # Post-processor to manifest AMI details
  post-processor "manifest" {
    output     = "${path.root}/packer-manifest.json"
    strip_path = true
    custom_data = {
      lab_name    = "test-windows"
      os_type     = "windows-server-2022"
      git_hash    = "9723951"
      build_time  = timestamp()
    }
  }
}
