# Auto-generated variables file for test-windows
# Generated by v2-ami-automation
#
# This file defines all variables used in the Packer template.
# Modify these values to customize your AMI build.

variable "lab_name" {
  type        = string
  description = "Name of the laboratory"
  default     = "test-windows"
}

variable "os_type" {
  type        = string
  description = "Operating system type"
  default     = "windows-server-2022"
}

variable "source_ami" {
  type        = string
  description = "Source AMI ID to build from"
  default     = "ami-0159172a5a821bafd"
}

variable "source_ami_name" {
  type        = string
  description = "Source AMI name for tagging"
  default     = "Windows_Server-2022-English-Full-Base-2025.11.12"
}

variable "instance_type" {
  type        = string
  description = "EC2 instance type for building the AMI"
  default     = "t3.medium"
}

variable "region" {
  type        = string
  description = "AWS region for building the AMI"
  default     = "us-east-1"
}

variable "volume_size" {
  type        = number
  description = "Root volume size in GB"
  default     = 30
}

variable "volume_type" {
  type        = string
  description = "Root volume type"
  default     = "gp3"
}

variable "encrypt_boot" {
  type        = bool
  description = "Encrypt the root volume"
  default     = true
}
